kind: Deployment
apiVersion: apps/v1
metadata:
  name: client-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: web 
  template:
    metadata:
      labels:
        component: web 
    spec:
      containers:
        - name: client
          image: phdocker85/41422:V5             
           ports: 
            - containerPort: 3000 
      restartPolicy: Always
